### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Sarah",
  "password": "123456", 
  "email": "Sarah3@test.com"
}

### Sessions create (login)                      
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "password": "123456", 
  "email": "Sarah@test.com"
}






### Address_users create 
Post http://localhost:3000/address_users.json
Authorization: Bearer eeyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjU3NDgxMDIzfQ.RlDsGmGmjcjZ8aMicKGbRXO3vC2In9F5W-9HJ4qlMAY

Content-Type: application/json

{
  "user_id": 3 ,
  "address_id": 2
}




### Addresses Show
GET http://localhost:3000/addresses/1.json

### Addresses Index
GET http://localhost:3000/addresses.json





### Users show 
GET http://localhost:3000/users/3.json




### Artifacts Index
GET http://localhost:3000/artifacts.json


### Artifacts show 
GET http://localhost:3000/artifacts/1.json


### Historicalevents Index
GET http://localhost:3000/historical_events.json



### Historicalevents show 
GET http://localhost:3000/historical_events/1.json







def index 
    @historical_events = HistoricalEvents.all
    render template: "historicalevents/index"
  end 

  def show
    @historical_events = Artifact.find_by(id: params[:id])
    render template: "historicalevents/show"
  end 